#!/bin/bash


scriptdir="$(dirname "$(readlink -f "$0")")"

if [[ -e ~/.bash_profile ]]; then
    echo "Moving ~/.bash_profile to ~/.bash_profile.bak"
    mv ~/.bash_profile ~/.bash_profile.bak
fi

if [[ -e ~/.bashrc ]]; then
    echo "Moving ~/.bashrc to ~/.bashrc.bak"
    mv ~/.bashrc ~/.bashrc.bak
fi

if [[ -e ~/.inputrc ]]; then
    echo "Moving ~/.inputrc to ~/.inputrc.bak"
    mv ~/.inputrc ~/.inputrc.bak
fi

echo "Linking $scriptdir/lib/bash_profile.bash to ~/.bash_profile"
ln -s "$scriptdir"/lib/bash_profile.bash ~/.bash_profile
echo "Linking $scriptdir/lib/bashrc.bash to ~/.bashrc"
ln -s "$scriptdir"/lib/bashrc.bash ~/.bashrc
echo "Linking $scriptdir/lib/inputrc to ~/.inputrc"
ln -s "$scriptdir"/lib/inputrc ~/.inputrc
